import type { Metadata } from 'next';
import { Inter } from 'next/font/google';
import { Global } from '@emotion/react';
import globalStyle from '@publishing/ui/foundation/global.style';

const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <Global styles={globalStyle} />
      <body className={inter.className}>{children}</body>
    </html>
  );
}
